include:
  - project: flywheel-io/scientific-solutions/etc/sse-qa-ci
    ref: 86f3649f27409ebe46ccada4dbf0bf0a75332b38
    file: ci/default.yml

variables:
  PYTEST_COV_FAIL_UNDER: 0  # Set pytest coverage to 0
  DEBUG: 0 # Set debug mode to print out executed command on qa-ci
  PUBLISH_POETRY: "false" # Set to true to allow CI to publish package to PYPI

publish:docker:
  rules:
    - if: $CI_COMMIT_SHA
      when: never
